// frontend/components/list/index.vue
<script setup>
import { ChevronDown, ChevronsUpDown, ChevronUp, RotateCw, Settings } from 'lucide-vue-next';

/**
 * @typedef Props
 * @property {import('hp-types').Compontent.List.Columns} columns
 * @property {import('hp-types').Compontent.List.Columns} columnsAvailable
 * @property {import('hp-types').Compontent.List.Rows} rows
 * @property {string} modelName
 * @property {() => void} onReload
 * @property {(size: number) => void} onPageSizeChange
 * @property {boolean} showSizeChanger
 * @property {boolean} showReload
 * @property {boolean} showSettings
 * @property {boolean} showPagination
 */

/**
 * @type {Props}
 */
// @ts-ignore
const props = defineProps([
  'columns',
  'columnsAvailable',
  'rows',
  'modelName',
  'onReload',
  'onPageSizeChange',
  'showSizeChanger',
  'showReload',
  'showSettings',
  'showPagination'
]);

const rowColumns = computed(() => props.columnsAvailable?.map((column) => column.value));

const selectedColumns = ref(['name', 'hostname', 'ip']);
/** @type {import('vue').Ref<null|string>} */
const sort = ref(null);
const pageSize = ref(25);

/** @param {Number} size */
function updatePageSize(size) {
  pageSize.value = size;

  /** @type {import('vue-router').RouteLocationNormalizedLoaded } */
  const route = useRoute();
  /** @type {import('vue-router').LocationQuery&{ page_size?: number }} */
  let query = route.query;

  if (Object.keys(query).includes('page_size')) {
    query.page_size = size;
  } else {
    // @ts-ignore
    query = { ...query, page_size: size };
  }
  console.log('PUSH', { path: route.path, query });
  useRouter().push({ path: route.path, query });
  
  props.onPageSizeChange(size);
}

/** @param {string} value */
function updateSort(value) {
  if (sort.value === value) {
    sort.value = `-${value}`;
  } else {
    sort.value = value;
  }
}
</script>

<template>
  <div v-bind="$attrs">
    <div class="w-full my-2 gap-2 flex justify-end">
      <span v-if="showSizeChanger" class="border rounded-md dark:border-slate-500">
        <button
          @click="updatePageSize(25)"
          class="px-1 rounded-md dark:hover:bg-slate-600"
        >
          25
        </button>
        <button
          @click="updatePageSize(50)"
          class="px-1 rounded-md dark:hover:bg-slate-600"
        >
          50
        </button>
        <button
          @click="updatePageSize(100)"
          class="px-1 rounded-md dark:hover:bg-slate-600"
        >
          100
        </button>
      </span>
      <button v-if="showReload" class="border rounded-md py-1 dark:border-slate-500 dark:hover:bg-slate-600" @click="onReload">
        <RotateCw class="h-4"/>
      </button>
      <DialogBtn v-if="showSettings">
        <template #button>
          <Settings class="h-4"/>
        </template>
        <template #header>
          <h2 class="px-2 py-1 text-2xl">Columns</h2>
        </template>
        <template #default>
          <InputCheckboxGroup :fields="columnsAvailable" v-model="selectedColumns"/>
        </template>
      </DialogBtn>
    </div>
    <table class="w-full">
      <thead>
        <tr class="font-semibold text-left">
          <th v-for="column in columnsAvailable" :key="column.value" v-show="selectedColumns.includes(column.value)" class="border h-10 border-slate-300 dark:border-slate-700">
            <button v-if="column.sortable" class="w-full text-left px-2 py-1 flex justify-between" @click="updateSort(column.value)">
              <span>
                {{ column.label }}
              </span>
              <span>
                <ChevronDown v-if="sort === column.value"/>
                <ChevronUp v-else-if="sort === `-${column.value}`"/>
                <ChevronsUpDown v-else/>
              </span>
            </button>
            <span v-else class="px-2 py-1">
              {{ column.label }}
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <ListRow v-for="row in rows" :row="row" :columns="rowColumns" :active-columns="selectedColumns" :key="row.id" :href="`${modelName}/${row.id}`"/>
      </tbody>
    </table>
    <ListPaginator v-if="showPagination" :count="100" :per-page="5"/>
  </div>
</template>

// frontend/src/lib/components/list/List.svelte
<script>
  /**
   * @typedef {Object} ColumnHeader
   * @property {string} label
   * @property {string} key
   * @property {boolean} sortable
  */

  /**
   * @typedef {{ columns: string[], href: null|string }} TableRow
  */

  /**
   * @callback onSortChange
   * @param {string} sortColumn
   * @param {boolean} sortDesc
   * @returns {void}
  */

	import { ChevronDown, ChevronUp, ChevronsUpDown } from "lucide-svelte";
	import Row from "./Row.svelte";

  /** @type {{ columns: ColumnHeader[], rows: TableRow[], onSortChange: onSortChange }} */
  const { columns, rows, onSortChange } = $props();

  /** @type {string|null} */
  let sortColumn = $state(null);
  let sortDesc = $state(true);

  /** @param {string} column */
  function onSortClick(column) {
    if (sortColumn === column) {
      sortDesc = !sortDesc;
    } else {
      sortColumn = column;
      sortDesc = true;
    }

    onSortChange(sortColumn, sortDesc);
  }
</script>

<table class='w-full'>
  <thead>
    <tr class='font-semibold text-left'>
      {#each columns as column}
        <th class='border h-10 border-slate-300 dark:border-slate-700'>
          {#if column.sortable }
            <button
              class='w-full h-full flex items-center justify-between pl-2 text-left hover:bg-slate-300 dark:hover:bg-slate-800 transition-all'
              onclick={() => onSortClick(column.key)}
            >
              <span>{column.label}</span>
              <span>
                {#if sortColumn === column.key}
                  {#if sortDesc}
                    <ChevronDown class='h-4'/>
                  {:else}
                    <ChevronUp class='h-4'/>
                  {/if}
                {:else}
                  <ChevronsUpDown class='h-4'/>
                {/if}
              </span>
            </button>
          {:else}
            <span class='pl-2'>
              {column.label}
            </span>
          {/if}
        </th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each rows as row}
      <Row columns={row.columns} href={row.href}/>
    {/each}
  </tbody>
</table>
