// frontend/src/lib/components/list/Row.svelte
<script>
  /** @type {{ columns: string[], href: null|string }} */
  const { columns, href=null } = $props();
</script>

<tr>
  {#each columns as column}
    <td class='border border-slate-300 dark:border-slate-700'>
      {#if href}
        <a {href} class='block pl-2 py-1'>
          {column}
        </a>
      {:else}
        {column}
      {/if}
    </td>
  {/each}
</tr>

// frontend/components/list/Row.vue
<script setup lang="ts">

defineProps<{
  row: { id: number }
  columns: string[]
  activeColumns: string[]
  href: string
}>();
</script>

<template>
  <tr :class="{ 'hover:bg-slate-800': href }">
    <td v-for="column in columns" v-show="activeColumns.includes(column)" class="border border-slate-300 dark:border-slate-700">
      <NuxtLink v-if="href" :to="href" class="block px-2 py-1 hover:cursor-pointer">
        {{ row[column] }}
      </NuxtLink>
      <span v-else class="block px-2 py-1">
        {{ row[column] }}
      </span>
    </td>
  </tr>
</template>
