// frontend/components/list/paginator/Link.vue
<script setup lang="ts">

defineProps<{
  href: string,
  active: boolean,
  current: boolean,
}>()
</script>

<template>
  <NuxtLink
    v-if="active"
    :to="href"
    :class="{ 'bg-slate-300': current, 'dark:bg-slate-700': current }"
    class="border select-none w-8 h-8 flex items-center justify-center border-slate-300 hover:bg-slate-300 dark:border-slate-700 dark:hover:bg-slate-700 cursor-pointer text-sm"
  >
    <slot></slot>
  </NuxtLink>
  <span
    v-else
    class="border select-none w-8 h-8 flex items-center justify-center border-slate-300 dark:border-slate-700 text-sm"
  >
    <slot></slot>
  </span>
</template>

// frontend/src/lib/components/paginator/Link.svelte
<script>
  /** @type {{ children: import('svelte').Snippet, href: string, active: boolean, current: boolean, props: any[] }} */
  const { children, href, active = false, current = false, ...props } = $props();
</script>

{#if active}
  <a
    {href}
    class:bg-slate-300={current}
    class:dark:bg-slate-700={current}
    {...props}
    class='border select-none w-8 flex items-center justify-center border-slate-300 hover:bg-slate-300 dark:border-slate-700 dark:hover:bg-slate-700'
  >
    {@render children()}
  </a>
{:else}
  <span
    class='border select-none w-8 flex items-center justify-center border-slate-300 dark:border-slate-700'
    {...props}
  >
    {@render children()}
  </span>
{/if}
